### ISSUE TITLE
Migrate plot recipe for plotting graphs over to LG?

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/PlotRecipes.jl#29]
I wonder if it would be a good idea to port the graph recipe to LG? Plot recipes are becoming the de-facto standard for plotting user types and LG is the de-facto standard for graphs in Julia. Having the recipe separate from the package seems odd to me.

Can you please explain the rationale?

cc: @sbromberger

**Comment by mkborregaard** [comment]
It's good to have a discussion on this. IMHO it would be obvious that LightGraphs should be self-sustainable in terms of Recipes - the reason for having it here, though, is that the recipes here (written by @tbreloff ) are more general and can be used for any kind of graph, or just a simple array of edges. It'd be great and meaningful to migrate the bit enclosed in the `if isinstalled("LightGraphs")` block to LightGraphs, which would make the functionality clearer, possibly avoid precompilation issues, and importantly make maintenance more straightforward, because all changes to LightGraphs could be directly reflected in the recipe. But the recipe still depends on the general graph recipe here, so the user would still be using PlotRecipes rather than Plots to do the Plots.
I'll be gone for the next month.

**Comment by juliohm** [comment]
Very well thought @mkborregaard, I will see what the recipe is like as of today and see what would be a good compromise. Maybe we should derive our own LG recipe that is independent but based on your implementation. I really like the idea of `RecipesBase.jl`, and I think we would benefit from having it in LG for future maintenance and additions.

**Comment by mkborregaard** [comment]
Sounds good. If you do choose to migrate the LightGraphs-specific code to LightGraphs (which really is the sensible thing to do IMHO) another advantage is that you'd have full freedom to modify it as you see fit, of course. Maybe @tbreloff should do the PR to make it obvious that he wrote the recipes.

**Comment by juliohm** [comment]
I won't be able to touch this any time soon, closing for now.
