### ISSUE TITLE
List of PlotRecipe packages

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/PlotRecipes.jl#32]
In the README, StatPlots.jl is included as well as a few illustrations of its plot recipes. I wonder if it wouldn't be a good idea to create a meta project on the JuliaPlots organization or a simple [awesome list](https://github.com/sindresorhus/awesome) with plot recipe packages instead?

This list would contain StatPlots.jl and any other plot recipe package contributed by the community. The package PlotRecipes.jl could be renamed to something more specific or could be break down into small packages that are easy to maintain.

Having a list instead of a package with a big REQUIRE file welcomes more contributions in my opinion. People would just write their recipes without caring too much about stability and other requirements. Issues would be opened separately and handled by the authors of a specific recipe who have the skills to fix the problems right away.

What are your thoughts on this? If you agree, please let me know and I can help setting up the list.

**Comment by mkborregaard** [comment]
I think it's worth considering. Two points:

1. Most recipes should live in the package defining the type. That is the intention of the system, and it makes maintenance a lot easier (meaning "makes maintenance possible" in practical terms). 
2. Some packages may be so basal in the julia system that they will not define plot recipes, but really should have. E.g. the DataFrames people may not want a plot recipe, but everyone else needs a recipe for DataFrames. StatPlots and PlotRecipes exists for this purpose.

It might be worth considering, for these packages, to have an atomized recipes ecosystem with glue packages, such as a GraphRecipes package for instance.

Having said that, none of the two packages with plot recipes have a big Require file at the moment. What is specifically the problem you wish to address?

Tagging @ChrisRackauckas @daschw @pkofod @Evizero

**Comment by ChrisRackauckas** [comment]
Isn't this just asking for the ecosystem page?

https://juliaplots.github.io/ecosystem/

**Comment by mkborregaard** [comment]
Yes, sort of, but I thought it also suggested breaking down PlotRecipes into minor chunks.

**Comment by ChrisRackauckas** [comment]
I think there is something to be said about PlotRecipes.jl just being a messy hodgepodge of recipes. I think StatPlots.jl should just be separate. StatPlots.jl handles its domain very well though. I think PlotRecipes.jl splitting to becomes a FinancePlots.jl and a GraphPlots.jl would make sense, but I am not sure there's actually enough code here to warrant it.

**Comment by mkborregaard** [comment]
I tend to agree. Or maybe just split off GraphRecipes to be a standalone package within the JuliaGraphs organisation, with perhaps the LightGraphs-specific stuff directly in LightGraphs , as we've discussed before, @juliohm ?

**Comment by juliohm** [comment]
Thank you for your replies @mkborregaard and @ChrisRackauckas. I agree with all that you said.

The proposal is to have a simple metapackage or simple list (perhaps the ecosystem page is all that is needed) pointing to various tiny plot recipe packages. PlotRecipes.jl can definitely be split into small chuncks that are more specific like GraphRecipes.jl for example. It would also make it easier to migrate the type recipes later on to packages like LightGraphs.jl if necessary.

Can we proceed with this idea? What do you suggest for the first steps?

**Comment by juliohm** [comment]
Do you agree in splitting PlotRecipes.jl into:

- [ ] GraphPlots.jl
- [ ] FinancePlots.jl
- [ ] ArcDiagramPlots.jl
- [ ] ASTPlots.jl
- [ ] TypeTreePlots.jl
- [ ] ShapePlots.jl
- [ ] PortfolioPlots.jl
- [x] StatPlots.jl

I don't have write access to create the repositories in the organization, but soon they are created I can submit PRs for each if you need help.

**Comment by tbreloff** [comment]
My $0.02... it's adding a lot of noise to break it up into 500 packages.
There's already too many in the org. But if others want this... 😎

**Comment by ChrisRackauckas** [comment]
Graphs makes sense since there's a lot of graphs. The others are like one recipe though.

**Comment by juliohm** [comment]
I think this is the way to got, break it down into small simple recipes that can be reused. Right now for instance I cannot depend on PlotRecipes.jl because some of the recipes depend on Plots.jl.

Hopefully at some point these 500 small recipes will cluster into dozens of recipes. Some may even becomes so popular that they can be shipped with Plots.jl or be incorported there.

**Comment by juliohm** [comment]
Packages with a single recipe should be fine. In my opinion we should promote this type of development. After some point the patterns will emerge and people will collaborate and categorize recipes, merge them into larger packages if necessary.

**Comment by juliohm** [comment]
Of course, if you have suggestions for a different split, I am all ears :+1:  The point is that a single PlotRecipes.jl is not modular enough.

**Comment by mkborregaard** [comment]
@juliohm It doesn't look like there's support for your plan. I think it is worth discussing, but tend to align with @ChrisRackauckas in seeing that Graphs could be split off but the rest should be kept together.

But back to what I originally said - what is the problem you're trying to solve? Let's address that instead of changing all of the org. It sounds like you want to depend on PlotRecipes but can't do that because it depends on Plots. This issue has been brought up before, and it is still open for discussion whether PlotRecipes should really depend on Plots. This is a problem e.g. for graphs, because any package that wants to leverage the graphplot user recipe must depend on PlotRecipes, a situation that isn't ideal.

What I'd suggest you do is to have a look at the graphing-related code, and come with a suggestion for moving functionality to the JuliaGraphs organisation. I'd say the generalized graphplot user recipe (which is consistent with any graph format, not just LightGraphs) could either have it's own package in the JuliaGraphs org (depending on NetworkLayout but not Plots) or be moved to NetworkLayout; the LightGraphs-specific stuff could be moved to LightGraphs (which should then depend on the GraphRecipe package) and the plot recipes here (AST trees etc) could continue living on PlotRecipes. But that's just a quick suggestion.

> it's adding a lot of noise to break it up into 500 packages.

@tbreloff good point on the org organisation. Although with Pkg3 (I guess it is coming now :-) ) it should become possible to install and depend on submodules within the same repo, meaning that a more modular structure could all still live in PlotRecipes.jl. That's for later, of course.

**Comment by mkborregaard** [comment]
How do you feel about moving out the graphs bit @tbreloff ? The other alternative is to go with @ChrisRackauckas suggestion and drop the Plots dep.

**Comment by juliohm** [comment]
Hi Michael, thank you for your reply. The main issue is that PlotRecipes.jl
is too inclusive and can grow arbitrarily without further split. The
dependency on Plots.jl is another issue that needs to be solved separately.

**Comment by mkborregaard** [comment]
> PlotRecipes.jl is too inclusive

Why?

**Comment by juliohm** [comment]
Right now it has 10 or so standalone recipes, in the future it may contain
hundreds. I don't see the issue in splitting the package. If I'm developing
a package that has nothing to do with graphs or finance for example, why
would I need to depend on other recipes? Let's say I'm only interested in
ASTPlots or TypeTreePlots to mimic Doxygen functionality in Documenter.jl.
I opened an issue there that would ideally be solved by reusing only these
recipes, and nothing else.

**Comment by juliohm** [comment]
Any updates on this issue?

**Comment by juliohm** [comment]
I am closing this since you don't seem to be interested.

**Comment by mkborregaard** [comment]
Do you say that because we haven't replied over the weekend? I have had many other things on my plate this weekend. That doesn't mean the issue is forgotten.

The current status of this issue is that I currently haven't seen any compelling arguments for splitting PlotRecipes up into a number of smaller packages. The main reason could be to avoid some dependencies, but the only dependencies here are (Stat-)Plots and NetworkLayout. 
I have given you a solution to the latter, in that I'd support moving the graph-related packages into their own package living in JuliaGraphs (as that is where NetworkLayout and LightGraphs is). If you're interested in doing that, try making a proposal for how it would look. That would be the package for you to extend if you wanted to mimic Doxygen functionality.

With regards to dropping the Plots dep, this has been argued before, and we will listen to arguments. The main argument against is that people are supposed to be able to just `using PlotRecipes` and then have a fully functional plotting ecosystem loaded. The main argument for is that most people don't actually seem to do that (they call `using PlotRecipes, Plots`), and for `user recipes` (e.g. the graph and dataframe recipes) it could sometimes be convenient to depend on PlotRecipes.

**Comment by juliohm** [comment]
Another good compelling reason is that of promoting collaboration. Right now, PlotRecipes.jl is a bunch of things mixed together that I have no clue where to start looking to contribute. Small recipes are easy to hack, modify and we know exactly (inside of the module) what is being used to achieve a particular plot.

For instance, my previous attempt to adapt the graph recipes to LG was a disaster. I couldn't isolate what is graph-related inside of the module in less than 10min and just moved on to do my own research because of time constraints.

The main problem with the Plots.jl ecosystem as of today is not functionality, but the lack of shared knowledge, documentation, and the effort to bring in new contributors. Only a few smart people (precisely the participants of this thread minus myself) are capable of fixing bugs, and improving upon the current recipes. Average Julia users just don't get it how recipes work.

If you change mind at some point in the future, I can help with the split. For now I am back to research mode with lots on my todo list.

**Comment by mkborregaard** [comment]
Yes, Plots is a quite complex piece of software, that's definitely agreed. 
Thanks for the offer to help - if you find the time and want to contribute down the line, the very best way of contributing is to engage with one of the 185 open issues and contribute a fix. But that's all up to you, I understand completely the many varied constraints we all have on our time.
